//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and
//     will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Utilities.Courses {
public partial class QHelper : IQHelper {
public static string Q0(Random random, Action<string, ushort> registerAnswer, bool isProof) {
var q = Quest_Q0(random, isProof);
string rval = q.GetQuestion(registerAnswer);
return rval;
} // Q0
public static TrueFalseQuestion Quest_Q0(Random random, bool isProof)
{
var q = new XyzQuestion(random, isProof);
q.Id = "Q0";
q.Marks = 5;
q.ShowMarks = false;
q.Stem = @"<p>Which of these Star Wars films was directed by George Lucas?</p>";
q.AddCorrects(
   @"<p>A New Hope</p>",
   @"<p>The Phantom Menace</p>",
   @"<p>Attack of the Clones</p>",
   @"<p>Revenge of the Sith</p>"
);
q.AddIncorrects(
   @"<p>The Empire Strikes Back</p>",
   @"<p>Return of the Jedi</p>",
   @"<p>The Force Awakens</p>",
   @"<p>The Last Jedi</p>",
   @"<p>The Rise of Skywalker</p>"
);
return q;
} // Quest_Q0
} // class
} // namespace
